export const ADD_TODO = 'ADD_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const DELETE_COMPLETED_TODOS = 'DELETE_COMPLETED_TODOS';
export const TOGGLE_ALL_TODOS = 'TOGGLE_ALL_TODOS';
export const CHANGE_TODO_TITLE = 'CHANGE_TODO_TITLE';
export const APPLY_FILTER = 'APPLY_FILTER';
export const PIN_TODO = 'PIN_TODO';
